name: LIVE - Sync OpenAPI definition to ReadMe

# Run workflow for every push to the `main` branch
on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      # Run GitHub Action to sync OpenAPI file at ./path-to-file.json
      - name: Sync Identity Action
        # We recommend specifying a fixed version, i.e. @v8
        # Docs: https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions
        uses: readmeio/rdme@v8
        with:
          rdme: openapi ./swagger/identity.json --key=${{ secrets.README_API_KEY }} --id=${{ secrets.REVIEW_API_DEFINITION_ID_IDENTITY }} 

      - name: Sync Process Action
        # We recommend specifying a fixed version, i.e. @v8
        # Docs: https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions
        uses: readmeio/rdme@v8
        with:
          rdme: openapi ./swagger/process.json --key=${{ secrets.README_API_KEY }} --id=${{ secrets.REVIEW_API_DEFINITION_ID_PROCESS }} 

      - name: Sync Form Action
        # We recommend specifying a fixed version, i.e. @v8
        # Docs: https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions
        uses: readmeio/rdme@v8
        with:
          rdme: openapi ./swagger/forms.json --key=${{ secrets.README_API_KEY }} --id=${{ secrets.REVIEW_API_DEFINITION_ID_FORMS }} 

      - name: Sync Dataset Action
        # We recommend specifying a fixed version, i.e. @v8
        # Docs: https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions
        uses: readmeio/rdme@v8
        with:
          rdme: openapi ./swagger/dataset.json --key=${{ secrets.README_API_KEY }} --id=${{ secrets.REVIEW_API_DEFINITION_ID_DATASET }} 

      - name: Sync Portal Action
        # We recommend specifying a fixed version, i.e. @v8
        # Docs: https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions
        uses: readmeio/rdme@v8
        with:
          rdme: openapi ./swagger/portal.json --key=${{ secrets.README_API_KEY }} --id=${{ secrets.REVIEW_API_DEFINITION_ID_PORTAL }} 

      - name: Sync Board Action
        # We recommend specifying a fixed version, i.e. @v8
        # Docs: https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions
        uses: readmeio/rdme@v8
        with:
          rdme: openapi ./swagger/board.json --key=${{ secrets.README_API_KEY }} --id=${{ secrets.REVIEW_API_DEFINITION_ID_BOARD }} 
          
